apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rcl452l1j-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rcl452l1j-java-quarkus-gitops